[package]
name = "creditra-credit"
version = "0.1.0"
edition = "2021"
description = "Creditra credit line Soroban contract"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
